# Site settings
title: Shahbaz Ahmed
header-img: img/home-bg.jpg
email: shahbazahmed1269@gmail.com
copyright_name: Shahbaz Ahmed
description: "My personal blog"
brand_name: "Shahbaz Ahmed's Blog"
repository: "https://github.com/shahbazahmed1269/shahbazahmed1269.github.io.git"
#baseurl: ""
url: "http://shahbaz.co"
twitter_username: shahbaz1269
github_username:  shahbazahmed1269
stackoverflow_username: 6937018/shahbaz-ahmed
disqus:
  shortname: shahbazahmed
share: true
#email_username:  shahbazahmed1269@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jemoji]
